### PR TITLE
Fix tiny typo

### PR DESCRIPTION
**Pull request by iblech**
Sorry for touching the last line (GitHub web editor).

### CODE REVIEW

**Comment by 2016rshah** [comment]
Thanks! And thanks for reading the post, what did you think?

**Comment by iblech** [comment]
I quite liked it! If you haven't checked it out already, I recommend having a look at "deriving" data types to obtain "zippers" or at combinatorial species. Both are related to the appearance of high school mathematics.

http://chris-taylor.github.io/blog/2013/02/13/the-algebra-of-algebraic-data-types-part-iii/
https://byorgey.wordpress.com/2009/07/24/introducing-math-combinatorics-species/

**Comment by 2016rshah** [comment]
Oh wow these are terrific thank you so much I will definitely look into them!

And another question, how did you happen upon this blog post? I haven't really publicized it anywhere or anything so I'm curious to know what led you to it :smiley:

**Comment by iblech** [comment]
A friend (@lukasepple) sent me a link to your BlaTeX repository. From there I followed the link in the description. :-)

**Pull request merged**
